try {
    throw "Hello";
} catch (error) {
    console.log("Caught");

}